CREATE TABLE IF NOT EXISTS user (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    bio TEXT,
    is_admin INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS product (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    price TEXT NOT NULL,
    image_url TEXT,
    seller_id TEXT NOT NULL
)
ALTER TABLE product ADD COLUMN is_blocked INTEGER DEFAULT 0;
ALTER TABLE user ADD COLUMN is_dormant INTEGER DEFAULT 0;
ALTER TABLE user ADD COLUMN failed_attempts INTEGER DEFAULT 0;
ALTER TABLE user ADD COLUMN is_locked INTEGER DEFAULT 0;
ALTER TABLE report ADD COLUMN created_at TEXT;
ALTER TABLE user ADD COLUMN is_locked INTEGER DEFAULT 0;
ALTER TABLE product ADD COLUMN image_url TEXT;